
#DB Connection Credentials

options:
	host: localhost
	port: 3306
	dbname: bpdata
	user: root
	#pass: 123456 Type your dbpass

	tag: &7[&6B&eP&7] #Tag for skript messages


#DB Connection Handler
on load:
	#set {conn_BPDATA} to the database "mysql://{@host}:{@port}/{@dbname}?user={@user}&password={@pass}&useSSL=false"
	set {conn_BPDATA} to the database "mysql://{@host}:{@port}/{@dbname}?user={@user}&password=&useSSL=false"